version: "3.9"


services:
  main_db:
    image: postgres:latest
    restart: always
    env_file: .env
    networks:
      - app_network
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data/
    ports:
      - ${POSTGRES_PORT}:5432
  redis:
    image: redis:alpine
    restart: always
    env_file: .env
    networks:
      - app_network
    ports:
      - ${REDIS_PORT}:6379


networks:
  app_network:
    driver: bridge
